services:
  - type: web
    name: flask-osm-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: HF_TOKEN
        value: YOUR_HF_TOKEN_HERE
